/*

#  Jelli Game Engine  #

Compiled from CoffeeScript.
In several parts ;)

*/

//  Screen:

// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Screen;

  Screen = function(canvas, context) {
    var doc;
    if (context == null) {
      context = "2d";
    }
    if (!(canvas instanceof HTMLCanvasElement)) {
      doc = document;
      canvas = doc.getElementById(canvas);
      if (!(canvas instanceof HTMLCanvasElement)) {
        canvas = void 0;
      }
    } else {
      doc = canvas.ownerDocument;
    }
    this.canvas = canvas;
    this.context = canvas ? canvas.getContext(context) : void 0;
    this.ownerDocument = doc;
    Object.defineProperties(this, {
      height: {
        get: function() {
          if (this.canvas) {
            return this.canvas.height;
          }
        },
        set: function(n) {
          if (this.canvas) {
            return this.canvas.height = n;
          }
        }
      },
      width: {
        get: function() {
          if (this.canvas) {
            return this.canvas.width;
          }
        },
        set: function(n) {
          if (this.canvas) {
            return this.canvas.width = n;
          }
        }
      }
    });
    return Object.freeze(this);
  };

  Screen.prototype = {
    clear: function() {
      if (!(this.canvas instanceof HTMLCanvasElement)) {
        return;
      }
      if (this.context instanceof CanvasRenderingContext2D) {
        return this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
      } else if (this.context instanceof WebGLRenderingContext) {
        return this.context.clear(this.context.COLOR_BUFFER_BIT | context.DEPTH_BUFFER_BIT);
      }
    }
  };

  Object.freeze(Screen.prototype);

  window.Screen = Screen;

}).call(this);
