manifest : http://marrus.xyz/jelli/JEL.elm
%%
%  Game Properties  %
Class : ENUMERATED
    GAME
Init : OPTIONAL STRING
Run : OPTIONAL STRING
Then : OPTIONAL STRING
%%
%  Views  %
Class : ENUMERATED
    VIEW
Id : STRING
Width : SHORT INTEGER
Height : SHORT INTEGER
Screen : MULTIPLE STRING
%%
%  Screens  %
Class : ENUMERATED
    SCREEN
Id : STRING
Type : ENUMERATED
    ANIMATION
    AREA
    STATIC
%%
%  Letters  %
Class : ENUMERATED
    LETTERS
Id : STRING
Source : STRING
Width : OPTIONAL SHORT INTEGER
Height : OPTIONAL SHORT INTEGER
Sprite Width : SHORT INTEGER
Sprite Height : SHORT INTEGER
Linefeed : SHORT INTEGER
Palette Color : OPTIONAL MULTIPLE STRING
%%
%  Tilesets  %
Class : ENUMERATED
    TILESET
Id : STRING
Source : STRING
Width : OPTIONAL SHORT INTEGER
Height : OPTIONAL SHORT INTEGER
Sprite Width : SHORT INTEGER
Sprite Height : SHORT INTEGER
Collisions : STRING
%%
%  Sheets  %
Class : ENUMERATED
    SHEET
Id : STRING
Source : STRING
Width : OPTIONAL SHORT INTEGER
Height : OPTIONAL SHORT INTEGER
Sprite Width : SHORT INTEGER
Sprite Height : SHORT INTEGER
%%
%  Areas  %
Class : ENUMERATED
    AREA
Id : OPTIONAL STRING
Map : OPTIONAL MULTIPLE STRING
Character : OPTIONAL MULTIPLE STRING
Image : OPTIONAL MULTIPLE STRING
Map : OPTIONAL MULTIPLE STRING
Init : OPTIONAL STRING
Run : OPTIONAL STRING
Then : OPTIONAL STRING
%%
%  Images  %
Class : ENUMERATED
    IMAGE
Id : STRING
Screen : STRING
Source : STRING
Width : OPTIONAL SHORT INTEGER
Height : OPTIONAL SHORT INTEGER
X Origin : OPTIONAL SHORT INTEGER
Y Origin : OPTIONAL SHORT INTEGER
%%
%  Spritelists  %
Class : ENUMERATED
    SPRITELIST
Id : STRING
Sheet : STRING
Box Width : OPTIONAL SHORT INTEGER
Box Height : OPTIONAL SHORT INTEGER
Box X Offset : OPTIONAL SHORT INTEGER
Box Y Offset : OPTIONAL SHORT INTEGER
X Origin : OPTIONAL SHORT INTEGER
Y Origin : OPTIONAL SHORT INTEGER
Sprite : MULTIPLE STRING
%%
%  Characters  %
Class : ENUMERATED
    CHARACTER
Id : STRING
Screen : STRING
Spritelist : STRING
Collides : OPTIONAL ENUMERATED
    NONE
    MAP
    CHARACTER
    BOTH
Init : OPTIONAL STRING
Run : OPTIONAL STRING
